### ISSUE TITLE
can not work in vite2.x?

### ISSUE THREAD

**Issue by ZedCoding** [XianZhengquan/postcss-px-to-viewport#2]
![image](https://user-images.githubusercontent.com/24578758/165880717-e5730870-5b60-45b0-b189-98ae98afebc2.png)

**Comment by XianZhengquan** [comment]
> ![image](https://user-images.githubusercontent.com/24578758/165880717-e5730870-5b60-45b0-b189-98ae98afebc2.png)

在项目根目录新建 postcss.config.js
<img width="482" alt="image" src="https://user-images.githubusercontent.com/46179450/165889930-cd821613-7ebc-43ed-9c06-2bbb391ba599.png">

**Comment by ZedCoding** [comment]
> > ![image](https://user-images.githubusercontent.com/24578758/165880717-e5730870-5b60-45b0-b189-98ae98afebc2.png)
> 
> 在项目根目录新建 postcss.config.js <img alt="image" width="482" src="https://user-images.githubusercontent.com/46179450/165889930-cd821613-7ebc-43ed-9c06-2bbb391ba599.png">

![image](https://user-images.githubusercontent.com/24578758/165904588-b2a8e00b-bd05-44dd-bf79-120e3123fcc1.png)
How to make "include" works?

**Comment by XianZhengquan** [comment]
> > > ![image](https://user-images.githubusercontent.com/24578758/165880717-e5730870-5b60-45b0-b189-98ae98afebc2.png)
> > 
> > 
> > 在项目根目录新建 postcss.config.js <img alt="image" width="482" src="https://user-images.githubusercontent.com/46179450/165889930-cd821613-7ebc-43ed-9c06-2bbb391ba599.png">
> 
> ![image](https://user-images.githubusercontent.com/24578758/165904588-b2a8e00b-bd05-44dd-bf79-120e3123fcc1.png) How to make "include" works?

需要配置 viewportUnit 属性，include 没有问题

**Comment by ZedCoding** [comment]
so weird！ set  same config and restart  but not work!
![image](https://user-images.githubusercontent.com/24578758/165914620-f7b2e836-7a69-4815-bb65-92b5401070d1.png)

**Comment by XianZhengquan** [comment]
> so weird！ set same config and restart but not work! ![image](https://user-images.githubusercontent.com/24578758/165914620-f7b2e836-7a69-4815-bb65-92b5401070d1.png)

老哥可以看一下详细的配置，或者 debugger 一下，我只是修改了部分结构和语法以支持postcss 8.x。原作者  https://github.com/evrone/postcss-px-to-viewport

**Comment by ZedCoding** [comment]
thanks a lot!
